Codefyn_Tech/urls.py
from django.contrib import admin
from django.urls import path, include  # new
from django.conf import settings  # new
from django.conf.urls.static import static  # new

from django.contrib.staticfiles.urls import staticfiles_urlpatterns

# Login Required for Admin Section Login
from django.contrib.auth.decorators import login_required

# OTP FOR AUTH
from django.contrib.auth.models import User
from pages.models import OnlineRequest, ContactUs, FeedBack
from sitesetting.models import (
    Faq,
)
from django_otp.admin import OTPAdminSite
from django_otp.plugins.otp_totp.models import TOTPDevice
from django_otp.plugins.otp_totp.admin import TOTPDeviceAdmin

# Debug


class OTPAdmin(OTPAdminSite):
    pass


admin_site = OTPAdmin(name="OTPAdmin")
admin_site.register(User)
admin_site.register(OnlineRequest)
admin_site.register(ContactUs)
admin_site.register(FeedBack)
admin_site.register(Faq)
admin_site.register(TOTPDevice, TOTPDeviceAdmin)


admin_site.login = login_required(
    admin_site.login
)  # for login requred for admin section


admin.site.site_header = "Codefyn "
admin.site.site_title = "Codefyn Portal"
admin.site.index_title = "Welcome to Codefyn"
urlpatterns = [
    path("admin/", admin.site.urls),
    # path("codefyn/secure/admin/dont-try-it/", admin_site.urls),
    # usermanage
    # localapp
    path("", include("services.urls")),
    path("accounts/", include("allauth.urls")),  # new
    path("", include("users.urls")),  # new
    path("", include("pages.urls")),
    path("", include("sitesetting.urls")),
    path("captcha/", include("captcha.urls")),
    
] + static(
    settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
)  # new
if settings.DEBUG:
    import debug_toolbar

    urlpatterns = [
        path("__debug__/", include(debug_toolbar.urls)),
    ] + urlpatterns

pages/urls.py
from django.urls import path

from pages.views import (
    HomePageView,
    AboutUs,
    FaqsView,
    TermsAndConditionsView,
    DisclamerView,
    OtpVerify,
    FeedBackFormView,
    SendHTMLMail,
    OtpReset,
    ContactFormView,
    OurWorks,
    ProjectDiscussFormView,
    PrivacyPolicyView,
    RefundPolicyView,
    LatestDesignsView,

)

app_name = "Home"
urlpatterns = [
    path("", HomePageView.as_view(), name="index"),
    path("latest-designs", LatestDesignsView.as_view(), name="latest_designs"),
    path("privacy-policy/", PrivacyPolicyView.as_view(), name="privacy_policy"),
    path("refund-policy/", RefundPolicyView.as_view(), name="refund_policy"),
    path("project-discuss/", ProjectDiscussFormView.as_view(), name="project_discuss"),
    path("works", OurWorks.as_view(), name="works"),
    path("otp-verify/", OtpVerify.as_view(), name="otp_verify"),
    path("otp-resend/", OtpReset, name="otp_reset"),
    path("aboutus/", AboutUs.as_view(), name="aboutus"),
    path("contactus/", ContactFormView.as_view(), name="contactus"),
    path("feedback/", FeedBackFormView.as_view(), name="feedback"),
    path("faqs/", FaqsView.as_view(), name="faqs"),
    path("disclamer/", DisclamerView.as_view(), name="disclamer"),
    path(
        "terms-conditions/",
        TermsAndConditionsView.as_view(),
        name="terms_and_conditions",
    ),  # new
]

services/urls.py
from django.urls import path, include

from .views import (
    WebDev,
    ServicesListViews,
    ServicesDetailViews,
    PersonalSites,
    Ecommerce,
    Corporate,
    Cms,
    Hrm,
    Portfollio,
    StaticSites,
    Blogs,
    DynamicWeb,
    BasicPack,
    StaticPackPrice,
    StaticPackPriceDetail,
    DynamicPackPriceDetail,
    CorporatePackPriceDetail,
    EcommercePackPriceDetail,
    LogoDesignView,
    CustomLogoDesignView,
    LogoReDesignView,
    BrandLogoDesignView,
    QuickCommerceView,
    CustomQuickCommerceView,
    QuickCommercePayementView,
    PerformanceAnalysisView,
    SoftDevView,
    GraphicsView,
    GraphicsSmView,
    GraphicsPackView,
    MarketingGraphicsView,
    DomainBookingView,
    DigitalMarketingView,
    SeoView,
)

app_name = "services"
urlpatterns = [
    path("seo/", SeoView.as_view(), name="seo"),
    path("digital-marketing/", DigitalMarketingView.as_view(), name="digital_marketing"),
    path("domain-booking/", DomainBookingView.as_view(), name="domain_booking"),
    path("marketing-graphics-designing/", MarketingGraphicsView.as_view(), name="marketing"),
    path("packing-graphics-designing/", GraphicsPackView.as_view(), name="graphics_pack"),
    path("social-media-graphics-designing/", GraphicsSmView.as_view(), name="graphics_sm"),
    path("graphics-designing/", GraphicsView.as_view(), name="graphics"),
    path("software-development/", SoftDevView.as_view(), name="soft_dev"),
    path("qucik-commerce-performance-analysis/", PerformanceAnalysisView.as_view(), name="quick_commerce_performance_analysis"),
    path("QucikCommercePaymentGetway/", QuickCommercePayementView.as_view(), name="quick_commerce_payment"),
    path("custom-qucik-commerce/", CustomQuickCommerceView.as_view(), name="custom_quick_commerce"),
    path("cucik-commerce/", QuickCommerceView.as_view(), name="quick_commerce"),
    path("custome-logo-design/", CustomLogoDesignView.as_view(), name="custom_logo_design"),
    path("brand-logo-design/", BrandLogoDesignView.as_view(), name="brand_logo_design"),
    path("logo-redesign/", LogoReDesignView.as_view(), name="logo_redesign"),
    path(
        "services/ecommerce-pack-detail",
        EcommercePackPriceDetail.as_view(),
        name="ecommerce_pack_detail",
    ),
    path("logo-design/", LogoDesignView.as_view(), name="logo_design"),
    path(
        "services/ecommerce-pack-detail",
        EcommercePackPriceDetail.as_view(),
        name="ecommerce_pack_detail",
    ),
    path(
        "services/corporate-pack-detail",
        CorporatePackPriceDetail.as_view(),
        name="corporate_pack_detail",
    ),
    path(
        "services/dynamic-pack-detail",
        DynamicPackPriceDetail.as_view(),
        name="dynamic_pack_detail",
    ),
    path(
        "services/static-pack-detail",
        StaticPackPriceDetail.as_view(),
        name="static_pack_price_detail",
    ),
    path(
        "services/static-pack-prices",
        StaticPackPrice.as_view(),
        name="static_pack_price",
    ),
    path(
        "services/basic-pack",
        BasicPack.as_view(),
        name="basic_pack",
    ),
    path(
        "services/web-services",
        WebDev.as_view(),
        name="web_dev",
    ),
    path(
        "services/dynamic-web",
        DynamicWeb.as_view(),
        name="dynamic_web",
    ),
    path(
        "services/personal-sites",
        PersonalSites.as_view(),
        name="personal_sites",
    ),
    path(
        "services/ecommerce",
        Ecommerce.as_view(),
        name="online_stores",
    ),
    path("services/corporate-web", Corporate.as_view(), name="corporate"),
    path("services/cms", Cms.as_view(), name="cms"),
    path("services/hrm", Hrm.as_view(), name="hrm"),
    path("services/portfolio", Portfollio.as_view(), name="portfollio"),
    path("services/blogs", Blogs.as_view(), name="blogs"),
    path("services/static-sites", StaticSites.as_view(), name="static_sites"),
    path("services/", ServicesListViews.as_view(), name="services"),
    path("services/<uuid:pk>", ServicesDetailViews.as_view(), name="service_detail"),
]

services/models.py
import uuid
from django.contrib.auth import get_user_model
from django.db import models
from django.urls import reverse


class Services(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    service_name = models.CharField(max_length=100)
    service_for = models.CharField(max_length=100)
    service_price = models.DecimalField(max_digits=6, decimal_places=2)
    bg_cover = models.ImageField(upload_to="services/", blank=True)

    def __str__(self):
        return self.service_name

    def get_absolute_url(self):  # new
        return reverse("service_detail", args=[str(self.id)])


class Reviews(models.Model):
    services = models.ForeignKey(
        Services,
        on_delete=models.CASCADE,
        related_name="reviews",
    )
    review = models.CharField(max_length=255)
    author = models.ForeignKey(
        get_user_model(),
        on_delete=models.CASCADE,
    )

    def __str__(self):
        return self.review

services/views.py
from django.views.generic import ListView, DetailView, TemplateView

from .models import Services
from sitesetting.models import Sites
from . import app_settings



class SeoView(TemplateView):
    template_name = "services/seo/seo." + app_settings.TEMPLATE_EXTENSION
    PAGE_TITLE = "SEO"
    extra_context = {
        "page_title": PAGE_TITLE,
    }



class DigitalMarketingView(TemplateView):
    template_name = "services/digital-marketing/digital-marketing." + app_settings.TEMPLATE_EXTENSION
    PAGE_TITLE = "Digital Marketing"
    extra_context = {
        "page_title": PAGE_TITLE,
    }



class DomainBookingView(TemplateView):
    template_name = "services/domain-booking/domain-booking." + app_settings.TEMPLATE_EXTENSION
    PAGE_TITLE = "Domian Booking"
    extra_context = {
        "page_title": PAGE_TITLE,
    }


class MarketingGraphicsView(TemplateView):
    template_name = "services/graphics/marketing." + app_settings.TEMPLATE_EXTENSION
    PAGE_TITLE = "Marketing Graphics Designing"
    extra_context = {
        "page_title": PAGE_TITLE,
    }

class GraphicsPackView(TemplateView):
    template_name = "services/graphics/graphics-pack." + app_settings.TEMPLATE_EXTENSION
    PAGE_TITLE = "Packing Graphics Designing"
    extra_context = {
        "page_title": PAGE_TITLE,
    }   
class GraphicsSmView(TemplateView):
    template_name = "services/graphics/graphics-sm." + app_settings.TEMPLATE_EXTENSION
    PAGE_TITLE = "Social Media Graphics Designing"
    extra_context = {
        "page_title": PAGE_TITLE,
    }   




class GraphicsView(TemplateView):
    template_name = "services/graphics/graphics." + app_settings.TEMPLATE_EXTENSION
    PAGE_TITLE = "Graphics Designing"
    extra_context = {
        "page_title": PAGE_TITLE,
    }   


class SoftDevView(TemplateView):
    template_name = "services/software-development/soft-dev." + app_settings.TEMPLATE_EXTENSION
    PAGE_TITLE = "Software Development"
    extra_context = {
        "page_title": PAGE_TITLE,
    }   



class PerformanceAnalysisView(TemplateView):
    template_name = "services/quick-commerce/quick-commerce-perfomance-analysis." + app_settings.TEMPLATE_EXTENSION
    PAGE_TITLE = "Quick Commerce Performance Analysis"
    extra_context = {
        "page_title": PAGE_TITLE,
    }   


class QuickCommerceView(TemplateView):
    template_name = "services/quick-commerce/quick-commerce." + app_settings.TEMPLATE_EXTENSION
    PAGE_TITLE = "Quick Commerce"
    extra_context = {
        "page_title": PAGE_TITLE,
    }   



class QuickCommercePayementView(TemplateView):
    template_name = "services/quick-commerce/quick-commerce-payment." + app_settings.TEMPLATE_EXTENSION
    PAGE_TITLE = " Quick Commerce Payment Getway Intregration"
    extra_context = {
        "page_title": PAGE_TITLE,
    }  



class CustomQuickCommerceView(TemplateView):
    template_name = "services/quick-commerce/custom-quick-commerce." + app_settings.TEMPLATE_EXTENSION
    PAGE_TITLE = "Custome Quick Commerce"
    extra_context = {
        "page_title": PAGE_TITLE,
    }   



class LogoReDesignView(TemplateView):
    template_name = "services/logodesign/logo-redesign." + app_settings.TEMPLATE_EXTENSION
    PAGE_TITLE = "Logo Redesign"
    extra_context = {
        "page_title": PAGE_TITLE,
    }   


class BrandLogoDesignView(TemplateView):
    template_name = "services/logodesign/brand-logo." + app_settings.TEMPLATE_EXTENSION
    PAGE_TITLE = "Brand Logo Design"
    extra_context = {
        "page_title": PAGE_TITLE,
    }


class LogoDesignView(TemplateView):
    template_name = "services/logodesign/logo-design." + app_settings.TEMPLATE_EXTENSION
    PAGE_TITLE = "Logo Design"
    extra_context = {
        "page_title": PAGE_TITLE,
    }


class CustomLogoDesignView(TemplateView):
    template_name = "services/logodesign/custom-logo-design." + app_settings.TEMPLATE_EXTENSION
    PAGE_TITLE = "Custom Logo Design"
    extra_context = {
        "page_title": PAGE_TITLE,
    }



class EcommercePackPriceDetail(TemplateView):
    """views"""

    template_name = (
        "services/e-commerce_pack_price_detail." + app_settings.TEMPLATE_EXTENSION
    )
    extra_context = {
        "page_title": "E-Commerce Pack Detail",
    }


class CorporatePackPriceDetail(TemplateView):
    """views"""

    template_name = (
        "services/corporate_pack_price_detail." + app_settings.TEMPLATE_EXTENSION
    )
    extra_context = {
        "page_title": "Corporate Pack Detail",
    }


class DynamicPackPriceDetail(TemplateView):
    """views"""

    template_name = (
        "services/dynamic_pack_price_detail." + app_settings.TEMPLATE_EXTENSION
    )
    extra_context = {
        "page_title": "Dynamic Pack Detail",
    }


class StaticPackPriceDetail(TemplateView):
    """views"""

    template_name = "services/static_price_detail." + app_settings.TEMPLATE_EXTENSION
    extra_context = {
        "page_title": "Static Pack Detail",
    }


class StaticPackPrice(TemplateView):
    """views"""

    template_name = "services/static_pack_price." + app_settings.TEMPLATE_EXTENSION
    extra_context = {
        "page_title": "Static Pack Price",
    }


class BasicPack(TemplateView):
    """views"""

    template_name = "services/basic_pack." + app_settings.TEMPLATE_EXTENSION
    extra_context = {
        "page_title": "Basic Pack",
    }


class WebDev(TemplateView):
    """views"""

    template_name = "services/webdev." + app_settings.TEMPLATE_EXTENSION
    extra_context = {
        "page_title": "Web Development Services",
    }


class DynamicWeb(TemplateView):
    """views"""

    template_name = "services/dynamic_web." + app_settings.TEMPLATE_EXTENSION
    extra_context = {
        "page_title": "Dynamic Websites",
    }


class Hrm(TemplateView):
    """views"""

    template_name = "services/HRM." + app_settings.TEMPLATE_EXTENSION
    extra_context = {
        "page_title": "HRM",
    }


class StaticSites(TemplateView):
    """views"""

    template_name = "services/static_sites." + app_settings.TEMPLATE_EXTENSION
    extra_context = {
        "page_title": "Static Sites",
    }


class Portfollio(TemplateView):
    """views"""

    template_name = "services/portfollio." + app_settings.TEMPLATE_EXTENSION
    extra_context = {
        "page_title": "Portfollio",
    }


class Blogs(TemplateView):
    """views"""

    template_name = "services/blogs." + app_settings.TEMPLATE_EXTENSION
    extra_context = {
        "page_title": "Blogs",
    }


class PersonalSites(TemplateView):
    """views"""

    template_name = "services/personal_site." + app_settings.TEMPLATE_EXTENSION
    extra_context = {
        "page_title": "Personal Sites",
    }


class Ecommerce(TemplateView):

    """View"""

    template_name = "services/ecommerce." + app_settings.TEMPLATE_EXTENSION
    extra_context = {
        "page_title": "E-commerce",
    }


class Corporate(TemplateView):

    """View"""

    template_name = "services/corporate." + app_settings.TEMPLATE_EXTENSION
    extra_context = {
        "page_title": "Mobile Web App",
    }


class Cms(TemplateView):

    """View"""

    template_name = "services/CMS." + app_settings.TEMPLATE_EXTENSION
    extra_context = {
        "page_title": "CMS",
    }


class ServicesListViews(ListView):
    model = Services
    context_object_name = "service_list"
    template_name = "services/service_list." + app_settings.TEMPLATE_EXTENSION


class ServicesDetailViews(DetailView):
    model = Services
    context_object_name = "service"  # new
    template_name = "services/service_details." + app_settings.TEMPLATE_EXTENSION

templates/services/service_details.html
{% extends 'layouts/_base.html' %}
{% block title %}{{ service.service_name }}{% endblock title %}
{% block content %}
<div class="service-detail">
    {% if service.bg_cover %}

    <img class="" style="height: 200px;width: 200px;" src="{{ service.bg_cover.url}}" 
    alt="{{ services.services_name }}">{% endif %}

<h2><a href="">{{ service.service_name }}</a></h2>
<p>{{ service.service_for }}</p>
<p>{{ service.service_price }}</p>

<h3>Reviews</h3>
<ul>
{% for review in service.reviews.all %}
<li>{{ review.review }} ({{ review.author }})</li>
{% endfor %}

</div>
{% endblock content %}

templates/services/service_list.html
{% extends 'layouts/_base.html' %}
{% block title %}Services{% endblock title %}
{% block content %}
{% for service in service_list %}
<div>
<h2><a href="{{ service.get_absolute_url }}">{{ service.service_name }}</a></h2>

</div>
{% endfor %}
{% endblock content %}

templates/services/services.html
{% extends 'layouts/_base.html' %} {% block content %} {% include
'includes/header.html' %} {% include 'includes/navbar.html' %} {% include
'includes/sidebar.html'%} {% include 'includes/footer.html' %} {%include
'includes/copyright.html' %} {% endblock %}

templates/services/webdev.html
{% extends 'layouts/_base.html'%} {% block content %}
<!-- slider -->
<section id="slider" class="slider">
  <div class="container">
      <div class="row">
          <div class="col-lg-6 col-xl-5">
              <div class="text-container">
                <ul class="d-block d-md-none">
                  <li class=""> <marquee behavior="scroll" direction="left">
                    Upto <span class="text-danger">50% </span><span class="text-warning">Discount </span> In Web Development Services...!</marquee>
                  </li>
                </ul>
                  <div class="slider-title">Welcome to Codefyn</div>
                  <h1 class="h1-large"><span class="text-danger">We </span> creates <spam class="text-success">Robust,</spam><span class="text-primary"> Stylish,</span> &
                    <span class="text-warning"> Efficient </span> <span class="text-muted">websites
                  </span><span class="text-info">In <span class="test-success">Best Price</span></h1>
                  <p class="p-large">A Perfect solution
                    for your small & medium business</p>
                  <a class="btnlg" href="tel:+917992200751">Call : + 917992200751 </a>

              </div> <!-- end of text-container -->
          </div> <!-- end of col -->
          <div class="col-lg-6 col-xl-7">
              <div class="image-container">
                  <img class="img-fluid" src="/static/codefyn-5.0/images/illustration.svg" alt="alternative">
              </div> <!-- end of image-container -->
          </div> <!-- end of col -->
      </div> <!-- end of row -->
  </div> <!-- end of container -->
</section> <!-- end of slider -->
<!-- end of slider -->


    <!-- Services -->
    <section id="service">
<div  class="bg-light pt-2 mt-3">
  <div class="container text-center">
    <div class="row">
      <div class="col">
        <header class="section-header wow fadeInUp">
          <h2>OUR WEB DEVELOPMENT SERVICES</h2>
          <p>We Deliver quality services with Professionals.</p>
        </header>

        <div class="row mb-3">
          <div class="col-6 col-md-3 mb-3">
            <div class="card shadow service-box">
              <img
                src="/static/codefyn-5.0/images/services/static.svg"
              />
              <div class="card-body">
                <p class="card-title pb-3">Static Websites</p>
                <a href="{% url 'services:static_sites' %}"  class="button"
                > Check Now</a
              >
              </div>
            </div>
          </div>

          <div class="col-6 col-md-3 mb-3">
            <div class="card shadow service-box">
              <img src="/static/codefyn-5.0/images/services/dynamic.svg" />
              <div class="card-body">
                <p class="card-title pb-3">Dynamic Website</p>
                <a href="{% url 'services:dynamic_web' %}"  class="button"
                > Check Now</a>

              </div>
            </div>
          </div>
          <div class="col-6 col-md-3 mb-3">
            <div class="card shadow service-box">
              <img src="/static/codefyn-5.0/images/services/ecom.svg" />
              <div class="card-body">
                <p class="card-title pb-3">E-Commerce</p>
                <a href="{% url 'services:online_stores' %}"  class="button"
                > Check Now</a
                >
              </div>
            </div>
          </div>

          <div class="col-6 col-md-3 mb-3">
            <div class="card shadow service-box">
              <img src="/static/codefyn-5.0/images/services/corporate.svg" />
              <div class="card-body">
                <p class="card-title pb-3">Corporate Website</p>
                <a href="{% url 'services:corporate' %}"  class="button"
                > Check Now</a
                >
              </div>
            </div>
          </div>
          </div>


      </section>
<!-- END -->
<section class="container">
<div class="text-center mt-3 ">
  <h2 class="fw-bold text-muted">
    Our Best <span class="text-primary">Web Design</span> & <span class="text-info">
      Development </span> <span class="test-muted">Services</span>
  </h2>
<div class="t-justify">
For the best mobile responsive and SEO friendly website development services in
India, contact codefyn,. In
contrast, 30% of online small businesses generate more than 25% of their revenue
online, more than 60% of small businesses have websites. Additionally, 31% of
business owners use web design firms. Our dedicated web developers have so far
successfully completed hundreds of website and web application projects for
industries with various business lines. We have created web applications from
the following domains: – E-Commerce Website Design & Development, Finance &
Banking, Content Management Systems, Blogging, Travel, E-Learning, Job Portal,
Retail etc. A company’s website design plays a key role in creating a first
impression on customers. And as a web design company, we totally get it! That’s
why we create innovative designs while using quality web development strategies
so you can be sure you’ll stay ahead of the competition. Call us for a FREE
website consultation to find out what websites you need to build your business
faster and with less effort. For the best website development services in India,
contact Codefyn today.
</div>
</div>
<div class="text-start mt-4">
<div class="row">
  <div class="col-md-6">
   <div class="shadow-sm p-3 mb-2 bg-white rounded">
    <img class="icon me-4" src="/static/codefyn-5.0/images/services/domain.png" />
     Domain & Hosting Services
  </div>
  </div>
  <div class="col-md-6">
    <div class="shadow-sm p-3 mb-2 bg-white rounded">
      <img class="icon me-4" src="/static/codefyn-5.0/images/services/webdevlop.png" />
      Website Designing & Development Service
    </div>
    </div>
</div>
<!--  -->
<div class="row">
  <div class="col-md-6">
    <div class="shadow-sm p-3 mb-2 bg-white rounded">
      <img class="icon me-4" src="/static/codefyn-5.0/images/services/responsive.png" />
       100% Responsive Web Design
    </div>
    </div>
  <div class="col-md-6">
    <div class="shadow-sm p-3 mb-2 bg-white rounded">
      <img class="icon me-4" src="/static/codefyn-5.0/images/services/corporate.png" />
    Corporate Web Design & Development
  </div>
 </div>
</div>
<!--  -->
<div class="row">
  <div class="col-md-6">
    <div class="shadow-sm p-3 mb-2 bg-white rounded">
      <img class="icon me-4" src="/static/codefyn-5.0/images/services/wordpressweb.png" />
    WordPress Website Development
  </div>
  </div>
  <div class="col-md-6">
    <div class="shadow-sm p-3 mb-2 bg-white rounded">
      <img class="icon me-4" src="/static/codefyn-5.0/images/services/ecommerce.png" />
      Ecommerce Website Development
  </div>
</div>
</div>
<!--  -->
<div class="row">
  <div class="col-md-6">
    <div class="shadow-sm p-3 mb-2 bg-white rounded">
      <img class="icon me-4" src="/static/codefyn-5.0/images/services/cmsweb.png" />
    CMS Website Design & Web Development
  </div>
  </div>
  <div class="col-md-6">
    <div class="shadow-sm p-3 mb-2 bg-white rounded">
      <img class="icon me-4" src="/static/codefyn-5.0/images/services/dweb.png" />
    Dynamic Website Design & Development
  </div>
  </div>
</div>
<!--  -->
<div class="row">
  <div class="col-md-6">
    <div class="shadow-sm p-3 mb-2 bg-white rounded">
      <img class="icon me-4" src="/static/codefyn-5.0/images/services/dweb.png" />
      Payment Gateway Integration
  </div>
  </div>
  <div class="col-md-6">
    <div class="shadow-sm p-3 mb-2 bg-white rounded">
      <img class="icon me-4" src="/static/codefyn-5.0/images/services/webre.png" />
      Website Redesign Service
    </div>
    </div>
   </div>
<!-- end -->

<!-- END -->
  </section>


<!-- End Feartures -->


<!-- end -->
</div>
</div>
</div>
</div>
<!-- -->
{% endblock %}